(() => {
  const heroSrc = 'maria-hero.jpg';
  const aboutSrc = 'maria-about.jpg';
  const links = {
    telegram:'https://t.me/maria_vadimovna_psy',
    max:'https://6max.ru/mariakoreneva',
    whatsapp:'https://wa.me/79183407717',
    email:'mailto:Maria_koreneva@list.ru'
  };
  const data = {
    ru:{
      brand:'Мария Коренева',nav:['Чем могу помочь','Примеры решений','Обо мне','Контакты'],menu:'Меню',cta:'Рассказать о задаче',
      hero:['Экономлю <span class="mk-accent">время и расходы</span> экспертов и бизнеса','Расскажите, что хотите сделать или упростить в своей работе. Я подберу подходящее решение и реализую его с помощью ИИ.','Посмотреть работы','Рассказать о задаче'],
      help:['ЧЕМ МОГУ ПОМОЧЬ','Не нужно быть специалистом в IT и разбираться в современных технологиях','Расскажите, что вы хотите сделать, упростить или ускорить в своей работе - я предложу, как это можно реализовать.'],
      services:[
        ['Нужно представить себя, свою услугу или проект?','Создам сайт, портфолио, онлайн-резюме или отдельную страницу, где ваши потенциальные клиенты, партнеры или работодатели смогут быстро найти нужную информацию и связаться с вами.','Вы получаете готовый сайт от одного специалиста - быстрее и выгоднее, чем заказывать разработку, дизайн и тексты отдельно.'],
        ['Много времени уходит на повторяющиеся рабочие задачи?','Создам персонального ИИ-помощника под вашу работу. Он сможет выполнять часть регулярных задач с учетом именно ваших требований.','ИИ-помощник экономит ваше время и может взять на себя часть работы, для которой раньше требовались другие специалисты.'],
        ['Хотите привлечь клиентов и выделиться среди конкурентов?','Создам тест, квиз, интерактивную игру, мини-сервис или другой необычный онлайн-формат для вашей аудитории.','Такой формат помогает выделиться среди конкурентов, привлечь внимание потенциальных клиентов и вовлечь их во взаимодействие.'],
        ['Приходится постоянно отвечать на одни и те же вопросы и выполнять однотипные действия?','Создам бота, который сможет отвечать на частые вопросы, выдавать материалы, проводить анкетирование, принимать заявки, помогать с записью или выполнять другой нужный сценарий.','Бот берет на себя часть работы администратора - вы экономите время и расходы на выполнение этих задач.'],
        ['Не знаете, как рассказать о себе и своих услугах?','Разберем вашу аудиторию и предложение, сформулируем позиционирование, оформим социальные сети и определим, о чем и как говорить с потенциальными клиентами.','Вы получаете все необходимое для продвижения в одном месте - от понимания своей аудитории до идей и оформления контента.']
      ],
      helpCta:['Не нашли здесь свою задачу?','Расскажите, что хотите сделать или упростить - подберем подходящее решение.','Рассказать о своей задаче'],
      solutions:['ПРИМЕРЫ РЕШЕНИЙ','От идеи до готового решения','Выберите интересующее направление, чтобы посмотреть примеры работ и их использования.'],
      solutionCards:[
        ['Сайты и лендинги','Сайты, лендинги, онлайн-резюме, портфолио и веб-платформы под разные задачи.','Смотреть работы'],['Персональные ИИ-помощники','Помощники, настроенные под конкретные рабочие задачи.','Смотреть примеры'],['Онлайн-инструменты','Интерактивные инструменты и мини-сервисы для работы и аудитории.','Смотреть примеры'],['Боты','Боты для общения с клиентами, анкетирования, выдачи материалов, заявок и других сценариев.','Смотреть примеры'],['Позиционирование и оформление','Анализ аудитории, позиционирование и оформление присутствия в социальных сетях.','Смотреть примеры']
      ],
      results:['РЕЗУЛЬТАТЫ В ЦИФРАХ','Меньше времени на рутину - быстрее к результату'],
      resultCards:[
        ['≈ В 2 РАЗА','Сократила свое время на часть рабочих задач благодаря ИИ','Сократила расходы на оплату работы других специалистов'],['3 ЧАСА → 10 МИНУТ','Экономия времени на подготовку поста','Экономия расходов на услуги копирайтера'],['2 ЧАСА → 5 МИНУТ','Экономия времени на создание основы контент-плана на месяц','Экономия расходов на услуги контент-менеджера'],['24/7','Бот отвечает клиентам, даже когда вы заняты или не на связи','Экономия расходов на часть задач администратора'],['1 НЕДЕЛЯ → 1-2 ДНЯ','Сокращение времени от идеи до запуска простого сайта','Экономия расходов - весь сайт, от текстов и дизайна до разработки, создает один специалист']
      ],
      process:['КАК Я РАБОТАЮ','От вашей задачи - к готовому решению'],
      steps:[['Вы рассказываете о задаче','Объясняете своими словами, что хотите сделать, изменить или упростить. Техническое задание не требуется.'],['Я предлагаю варианты','Показываю, как можно решить задачу и какие инструменты для этого подойдут.'],['Мы выбираем решение','Согласовываем подходящий вариант, результат, сроки и стоимость.'],['Я реализую','Создаю и настраиваю решение под вашу задачу.'],['Вы получаете готовый результат','Передаю готовый проект и объясняю, как им пользоваться.']],
      about:['ОБО МНЕ','Мария Коренева','Психология + наука + ИИ','Я - психолог, кандидат педагогических наук, доцент. Более 20 лет работаю с людьми и занимаюсь научной работой. Сегодня соединяю этот опыт с возможностями искусственного интеллекта.','Посмотреть сертификаты'],
      aboutCards:[['ПСИХОЛОГИЯ','Понимаю людей и аудиторию - что для них важно, что привлекает внимание и помогает принять решение.'],['НАУКА','Умею работать с большим объемом информации, анализировать, находить главное и выстраивать понятную структуру.'],['ИИ','Создаю с помощью ИИ сайты, персональных помощников, ботов и онлайн-инструменты.']],
      final:['ЕСТЬ ЗАДАЧА ИЛИ ИДЕЯ?','Расскажите, что хотите сделать, изменить или упростить','Я помогу определить, какое решение подойдет именно для вашей задачи.','Рассказать о задаче'],
      contacts:'КОНТАКТЫ',self:'Самозанятая',certificates:'Сертификаты'
    },
    en:{
      brand:'Maria Koreneva',nav:['How I Can Help','Solutions','About Me','Contacts'],menu:'Menu',cta:'Tell Me About Your Project',
      hero:['Helping experts and businesses save <span class="mk-accent">time and money</span>','Tell me what you&apos;d like to create or streamline in your work. I&apos;ll find the right solution and build it using AI.','View Projects','Tell Me About Your Project'],
      help:['HOW I CAN HELP','You don&apos;t need to be an IT expert or understand complex technology','Tell me what you&apos;d like to create, simplify, or speed up in your work, and I&apos;ll suggest a practical way to make it happen.'],
      services:[
        ['Need to present yourself, your service, or your project?','I&apos;ll create a website, portfolio, online résumé, or dedicated page where potential clients, partners, or employers can quickly find the information they need and contact you.','You get a complete website from one specialist - faster and more cost-effective than hiring separate people for development, design, and copy.'],
        ['Spending too much time on repetitive work?','I&apos;ll create a personal AI assistant tailored to your work. It can handle part of your routine tasks based on your specific requirements.','An AI assistant saves you time and can take over some of the work that previously required other specialists.'],
        ['Want to attract clients and stand out from competitors?','I&apos;ll create a test, quiz, interactive game, mini-service, or another engaging online format for your audience.','This kind of format helps you stand out, attract potential clients, and encourage them to interact with your content or offer.'],
        ['Do you keep answering the same questions and repeating the same tasks?','I&apos;ll create a bot that can answer frequently asked questions, deliver materials, run questionnaires, collect inquiries, assist with bookings, or follow another workflow you need.','The bot can take over part of an administrator&apos;s routine work, saving you both time and operating costs.'],
        ['Not sure how to present yourself and your services?','We&apos;ll clarify your audience and offer, shape your positioning, refine your social media presence, and determine what to communicate to potential clients and how to communicate it.','You get the essentials for your promotion in one place - from understanding your audience to content ideas and presentation.']
      ],
      helpCta:['Don&apos;t see your task here?','Tell me what you&apos;d like to create or simplify, and we&apos;ll find the right solution.','Tell Me About Your Project'],
      solutions:['SOLUTIONS','From Idea to Finished Solution','Choose an area to see examples of projects and how they can be used.'],
      solutionCards:[['Websites and Landing Pages','Websites, landing pages, online resumes, portfolios, and web platforms for different needs.','View Projects'],['Personal AI Assistants','AI assistants tailored to specific work tasks.','View Examples'],['Online Tools','Interactive tools and mini-services for your work and your audience.','View Examples'],['Bots','Bots for client communication, questionnaires, content delivery, inquiries, and other workflows.','View Examples'],['Positioning and Presentation','Audience analysis, positioning, and a clear, consistent social media presence.','View Examples']],
      results:['RESULTS IN NUMBERS','Less Time on Routine Tasks - Faster Results'],
      resultCards:[['≈ 2×','Reduced the time I spend on some work tasks by using AI','Reduced costs for work that previously required other specialists'],['3 HOURS → 10 MINUTES','Time saved on preparing a social media post','Reduced costs for copywriting'],['2 HOURS → 5 MINUTES','Time saved on creating the foundation of a monthly content plan','Reduced costs for content management'],['24/7','A bot can respond to clients even when you&apos;re busy or offline','Reduced costs for part of an administrator&apos;s routine tasks'],['1 WEEK → 1-2 DAYS','Less time from idea to launch for a simple website','Reduced costs because one specialist handles the entire website - from copy and design to development']],
      process:['HOW I WORK','From Your Task to a Finished Solution'],
      steps:[['You Tell Me About Your Task','Explain in your own words what you&apos;d like to create, change, or simplify. You don&apos;t need to prepare a technical brief.'],['I Suggest Options','I show you how the task can be solved and which tools would work best.'],['We Choose the Solution','We agree on the right approach, expected result, timeline, and cost.'],['I Build It','I create and configure the solution for your specific task.'],['You Receive the Finished Result','I deliver the finished project and explain how to use it.']],
      about:['ABOUT ME','Maria Koreneva','Psychology + Research + AI','I&apos;m a psychologist with a PhD in Education and an Associate Professor. I&apos;ve worked with people and in academic research for more than 20 years. Today, I combine that experience with the capabilities of AI.','View certificates'],
      aboutCards:[['PSYCHOLOGY','I understand people and audiences - what matters to them, what captures their attention, and what helps them make decisions.'],['RESEARCH','I know how to work with large amounts of information, analyze it, identify what matters most, and turn it into a clear structure.'],['AI','I use AI to create websites, personal assistants, bots, and online tools.']],
      final:['HAVE A TASK OR AN IDEA?','Tell Me What You&apos;d Like to Create, Change, or Simplify','I&apos;ll help you identify the solution that best fits your task.','Tell Me About Your Project'],
      contacts:'CONTACTS',self:'Self-employed',certificates:'Certificates'
    }
  };
  const langSwitch = '<div class="mk-lang" aria-label="Language"><button type="button" data-lang="ru">RU</button><span>|</span><button type="button" data-lang="en">EN</button></div>';
  const contactLinks = () => Object.entries({telegram:'Telegram',max:'MAX',whatsapp:'WhatsApp',email:'Email'}).map(([key,label])=>`<a class="mk-contact-link" href="${links[key]}"${key==='email'?'':` target="_blank" rel="noopener noreferrer"`}>${label}</a>`).join('');
  const render = (lang='ru') => {
    const t=data[lang];
    document.documentElement.lang=lang;
    document.title=lang==='ru'?'Мария Коренева — цифровые решения для экспертов и бизнеса':'Maria Koreneva — Digital Solutions for Experts and Businesses';
    document.body.innerHTML=`
      <header class="mk-header"><div class="mk-shell mk-header-inner"><a class="mk-brand" href="#home">${t.brand}</a><nav class="mk-nav"><a href="#services">${t.nav[0]}</a><a href="#projects">${t.nav[1]}</a><a href="#about">${t.nav[2]}</a><a href="#contacts">${t.nav[3]}</a></nav>${langSwitch}<a class="mk-button mk-button-primary mk-header-cta" href="#contacts">${t.cta}</a><button class="mk-menu-button" type="button" aria-label="${t.menu}" aria-expanded="false"><span></span></button></div><div class="mk-mobile-menu"><a href="#services">${t.nav[0]}</a><a href="#projects">${t.nav[1]}</a><a href="#about">${t.nav[2]}</a><a href="#contacts">${t.nav[3]}</a><div class="mk-mobile-tools">${langSwitch}<a class="mk-button mk-button-primary" href="#contacts">${t.cta}</a></div></div></header>
      <main>
        <section class="mk-hero mk-reveal" id="home"><div class="mk-shell mk-hero-grid"><div><h1>${t.hero[0]}</h1><p class="mk-hero-copy">${t.hero[1]}</p><div class="mk-actions"><a class="mk-button mk-button-primary" href="#projects">${t.hero[2]}</a><a class="mk-button" href="#contacts">${t.hero[3]}</a></div></div><div class="mk-photo mk-hero-photo"><img src="${heroSrc}" alt="${t.brand}"></div></div></section>
        <section class="mk-section mk-section-alt mk-reveal" id="services"><div class="mk-shell"><div class="mk-kicker">${t.help[0]}</div><h2 class="mk-title">${t.help[1]}</h2><p class="mk-lead">${t.help[2]}</p><div class="mk-five-grid">${t.services.map((x,i)=>`<article class="mk-card"><div class="mk-num">${String(i+1).padStart(2,'0')}</div><h3>${x[0]}</h3><p>${x[1]}</p><div class="mk-benefit">${x[2]}</div></article>`).join('')}</div><div class="mk-inline-cta"><div><h3>${t.helpCta[0]}</h3><p>${t.helpCta[1]}</p></div><a class="mk-button mk-button-primary" href="#contacts">${t.helpCta[2]}</a></div></div></section>
        <section class="mk-section mk-reveal" id="projects"><div class="mk-shell"><div class="mk-kicker">${t.solutions[0]}</div><h2 class="mk-title">${t.solutions[1]}</h2><p class="mk-lead">${t.solutions[2]}</p><div class="mk-solutions">${t.solutionCards.map((x,i)=>`<article class="mk-card mk-solution"><div class="mk-num">${String(i+1).padStart(2,'0')}</div><h3>${x[0]}</h3><p>${x[1]}</p>${i===0?`<a class="mk-card-action" href="websites.html${lang==='en'?'?lang=en':''}">${x[2]} →</a>`:i===1?`<a class="mk-card-action" href="ai-assistants.html${lang==='en'?'?lang=en':''}">${x[2]} →</a>`:i===2?`<a class="mk-card-action" href="online-tools.html${lang==='en'?'?lang=en':''}">${x[2]} →</a>`:i===3?`<a class="mk-card-action" href="bots.html${lang==='en'?'?lang=en':''}">${x[2]} →</a>`:i===4?`<a class="mk-card-action" href="positioning.html${lang==='en'?'?lang=en':''}">${x[2]} →</a>`:`<span class="mk-card-action">${x[2]} →</span>`}</article>`).join('')}</div></div></section>
        <section class="mk-section mk-section-alt mk-results mk-reveal"><div class="mk-shell"><div class="mk-kicker">${t.results[0]}</div><h2 class="mk-title">${t.results[1]}</h2><div class="mk-five-grid">${t.resultCards.map(x=>`<article class="mk-card"><div class="mk-big">${x[0]}</div><p class="mk-result-line"><span class="mk-plus">+</span> ${x[1]}</p><p class="mk-result-line"><span class="mk-plus">+</span> ${x[2]}</p></article>`).join('')}</div></div></section>
        <section class="mk-section mk-process mk-reveal"><div class="mk-shell"><div class="mk-kicker">${t.process[0]}</div><h2 class="mk-title">${t.process[1]}</h2><div class="mk-five-grid">${t.steps.map((x,i)=>`<article class="mk-card"><div class="mk-num">${String(i+1).padStart(2,'0')}</div><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></div></section>
        <section class="mk-section mk-section-alt mk-reveal" id="about"><div class="mk-shell mk-about-grid"><div><div class="mk-kicker">${t.about[0]}</div><h2 class="mk-title">${t.about[1]}</h2><div class="mk-formula">${t.about[2]}</div><p class="mk-about-copy">${t.about[3]}</p><div class="mk-about-cards">${t.aboutCards.map(x=>`<div class="mk-about-card"><b>${x[0]}</b>${x[1]}</div>`).join('')}</div><a class="mk-button mk-button-primary" href="certificates.html${lang==='en'?'?lang=en':''}">${t.about[4]}</a></div><div class="mk-photo mk-about-photo"><img src="${aboutSrc}" alt="${t.about[1]}"></div></div></section>
        <section class="mk-section mk-final mk-reveal"><div class="mk-shell"><div class="mk-kicker">${t.final[0]}</div><h2 class="mk-title">${t.final[1]}</h2><p class="mk-lead">${t.final[2]}</p><div class="mk-actions"><a class="mk-button mk-button-primary" href="#contacts">${t.final[3]}</a></div></div></section>
        <section class="mk-section mk-section-alt mk-contacts mk-reveal" id="contacts"><div class="mk-shell"><div class="mk-kicker">${t.contacts}</div><div class="mk-contact-grid">${contactLinks()}</div></div></section>
      </main>
      <footer class="mk-footer"><div class="mk-shell mk-footer-inner"><div class="mk-identity"><strong>${t.brand}</strong><span>${t.self}</span><span>ИНН 230908750806</span></div><div class="mk-footer-links"><a href="${links.telegram}" target="_blank" rel="noopener noreferrer">Telegram</a><a href="${links.max}" target="_blank" rel="noopener noreferrer">MAX</a><a href="${links.whatsapp}" target="_blank" rel="noopener noreferrer">WhatsApp</a><a href="${links.email}">Email</a></div></div></footer>`;
    document.querySelectorAll('[data-lang]').forEach(btn=>{btn.setAttribute('aria-pressed',String(btn.dataset.lang===lang));btn.addEventListener('click',()=>render(btn.dataset.lang));});
    const menu=document.querySelector('.mk-mobile-menu'),menuBtn=document.querySelector('.mk-menu-button');
    const closeMenu=()=>{menu.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')};
    menuBtn.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open))});
    menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
    document.addEventListener('click',e=>{if(!menu.contains(e.target)&&!menuBtn.contains(e.target))closeMenu()},{once:true});
    document.documentElement.classList.add('enhanced');
    const reveal=document.querySelectorAll('.mk-reveal');
    if(!('IntersectionObserver' in window)){reveal.forEach(el=>el.classList.add('mk-visible'));return}
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{entry.target.classList.toggle('mk-visible',entry.isIntersecting)}),{threshold:.1});
    reveal.forEach(el=>observer.observe(el));
  };
  render(new URLSearchParams(location.search).get('lang')==='en'?'en':'ru');
})();
